name: Build IOS
run-name: Build IOS
on:
  workflow_dispatch: {}
jobs:
  Build_IOS:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64
    - run: sudo xcode-select --switch /Applications/Xcode_14.3.1.app
    - run: flutter pub get
    - run: flutter build ios --release --no-codesign
    - run: |
        mkdir -p /Users/runner/work/PicaComicTest/PicaComicTest/build/ios/iphoneos/Payload
        mv /Users/runner/work/PicaComicTest/PicaComicTest/build/ios/iphoneos/Runner.app /Users/runner/work/PicaComicTest/PicaComicTest/build/ios/iphoneos/Payload
        cd /Users/runner/work/PicaComicTest/PicaComicTest/build/ios/iphoneos/
        zip -r app-ios.ipa Payload
    - uses: actions/upload-artifact@v4
      with:
        name: app-ios.ipa
        path: /Users/runner/work/PicaComicTest/PicaComicTest/build/ios/iphoneos/app-ios.ipa
