name: Build IOS
run-name: Build IOS
on:
  workflow_dispatch: {}
  push:
    tags:
      - 'v*.*.*'  # 仅在带有版本标签的推送时触发
jobs:
  Build_IOS:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v3
    - uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        architecture: x64
    - run: sudo xcode-select --switch /Applications/Xcode_14.3.1.app
    - run: flutter pub get
    - run: flutter build ios --release --no-codesign
    - run: |
        mkdir -p /Users/runner/work/PicaComicTest/PicaComicTest/build/ios/iphoneos/Payload
        mv /Users/runner/work/PicaComicTest/PicaComicTest/build/ios/iphoneos/Runner.app /Users/runner/work/PicaComicTest/PicaComicTest/build/ios/iphoneos/Payload
        cd /Users/runner/work/PicaComicTest/PicaComicTest/build/ios/iphoneos/
        zip -r app-ios.ipa Payload
    - uses: actions/upload-artifact@v4
      with:
        name: app-ios.ipa
        path: /Users/runner/work/PicaComicTest/PicaComicTest/build/ios/iphoneos/app-ios.ipa

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: 4.2
        release_name: Release 4.2
        draft: false
        prerelease: false

    - name: Upload IPA to Release
      id: upload_release_asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: /Users/runner/work/PicaComicTest/PicaComicTest/build/ios/iphoneos/app-ios.ipa
        asset_name: app-ios.ipa
        asset_content_type: application/octet-stream
